#include <components/esm4/physicalcombat.hpp>
#include <components/esm4/combatsettings.hpp>
#include <components/esm4/loadgmst.hpp>
#include <array>
#include <algorithm>
#include <utility>
#include <gtest/gtest.h>
#include <cmath>
#include <limits>
#include <random>

namespace
{
    // Independently decoded installed settings plus verified absent initializers.
    // See M15-NATIVE-RULE-PROVENANCE.md; never generated by production helpers.
    const ESM4::PhysicalCombatSettings installed{ -20, .4f, 1.f, .5f, .5f, .2f, 1.5f, .5f, .5f, .75f, .5f };
}

TEST(ESM4PhysicalCombat, LuckAdjustedSkillClampsAfterAdjustment)
{
    struct Case { int skill; int luck; float expected; };
    for (const auto& c : {Case{0, 50, 0}, {1, 50, 1}, {50, 50, 50}, {100, 50, 100},
             {101, 50, 100}, {50, 0, 30}, {50, 100, 70}, {0, 0, 0},
             {19, 0, 0}, {20, 0, 0}, {21, 0, 1}, {79, 100, 99}, {80, 100, 100},
             {81, 100, 100}, {-100, 50, 0}, {1000, 1000, 100}})
        EXPECT_FLOAT_EQ(ESM4::effectiveCombatSkill(c.skill, c.luck, installed), c.expected);
    EXPECT_NEAR(ESM4::effectiveCombatSkill(50, 49, installed), 49.6f, 0.00001f);
    EXPECT_NEAR(ESM4::effectiveCombatSkill(50, 51, installed), 50.4f, 0.00001f);
}

TEST(ESM4PhysicalCombat, FatigueUsesNativeSettingsWithoutRatioClamping)
{
    for (const auto& pair : {std::pair{-1.f, 0.f}, {0.f, .5f}, {.5f, .75f}, {1.f, 1.f}, {2.f, 1.5f}})
        EXPECT_FLOAT_EQ(ESM4::combatFatigueMultiplier(pair.first, installed), pair.second);
    const float below = std::nextafter(1.f, 0.f), above = std::nextafter(1.f, 2.f);
    EXPECT_LE(ESM4::combatFatigueMultiplier(below, installed), 1.f);
    // Half of one float ULP rounds back to even 1; the next ratio does not.
    EXPECT_EQ(ESM4::combatFatigueMultiplier(above, installed), 1.f);
    EXPECT_GT(ESM4::combatFatigueMultiplier(std::nextafter(above, 2.f), installed), 1.f);
    auto compiled = installed;
    compiled.mFatigueBase = 1.25f;
    EXPECT_FLOAT_EQ(ESM4::combatFatigueMultiplier(1.f, compiled), 1.25f);
}

TEST(ESM4PhysicalCombat, WeaponTermsPreserveRepairedConditionAndAttributeCap)
{
    ESM4::WeaponDamageInput input{50, 50, 50, 100, .5f, .5f};
    // 100*.5 * (.5+.5*.5) * (.2+1.5*.5) * (.75+.5*.5) * (.5+.5*.5).
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), 26.71875f, .00001f);
    input.mAttackMultiplier = 2;
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), 53.4375f, .00002f);
    input = {100, 50, 100, 100, 1.25f, 1.f};
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), 119.53125f, .00003f);
    for (int attribute : {99, 100, 101, 1000})
    {
        input.mAttribute = attribute;
        EXPECT_NEAR(ESM4::weaponDamage(input, installed), attribute == 99 ? 119.053125f : 119.53125f, .00003f);
    }
    input = {0, 50, 0, 100, 0.f, 0.f};
    EXPECT_FLOAT_EQ(ESM4::weaponDamage(input, installed), 1.875f);
    input.mIgnoreFatigue = true;
    EXPECT_FLOAT_EQ(ESM4::weaponDamage(input, installed), 3.75f);
    input.mBaseDamage = 0;
    EXPECT_FLOAT_EQ(ESM4::weaponDamage(input, installed), 0.f);
    input.mBaseDamage = 1;
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), .0375f, .000001f);
    input.mBaseDamage = 65535;
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), 2457.5625f, .001f);
    input.mAttackMultiplier = 0;
    EXPECT_FLOAT_EQ(ESM4::weaponDamage(input, installed), 0.f);
}

TEST(ESM4PhysicalCombat, InvalidInputsAndOverflowNeverBecomeDamage)
{
    ESM4::WeaponDamageInput input{50, 50, 50, 100, 1.f, 1.f};
    for (float value : {std::numeric_limits<float>::quiet_NaN(), std::numeric_limits<float>::infinity(),
             -std::numeric_limits<float>::infinity()})
    {
        auto bad = input;
        bad.mFatigueRatio = value;
        EXPECT_THROW(ESM4::weaponDamage(bad, installed), std::invalid_argument);
        bad = input;
        bad.mConditionRatio = value;
        EXPECT_THROW(ESM4::weaponDamage(bad, installed), std::invalid_argument);
        EXPECT_THROW(ESM4::combatFatigueMultiplier(value, installed), std::invalid_argument);
        auto settings = installed;
        settings.mLuckSkillMultiplier = value;
        EXPECT_THROW(ESM4::effectiveCombatSkill(50, 50, settings), std::invalid_argument);
    }
    input.mConditionRatio = -1;
    EXPECT_THROW(ESM4::weaponDamage(input, installed), std::invalid_argument);
    input.mConditionRatio = 1;
    input.mAttribute = -1;
    EXPECT_THROW(ESM4::weaponDamage(input, installed), std::invalid_argument);
    input.mAttribute = 50;
    input.mAttackMultiplier = -1;
    EXPECT_THROW(ESM4::weaponDamage(input, installed), std::invalid_argument);
    input.mAttackMultiplier = std::numeric_limits<float>::max();
    EXPECT_THROW(ESM4::weaponDamage(input, installed), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, NativeSettingsOverrideCompiledPhysicalDefaults)
{
    const auto compiled = ESM4::buildPhysicalCombatSettings({});
    EXPECT_FLOAT_EQ(compiled.mFatigueBase, 1.25f);
    EXPECT_FLOAT_EQ(compiled.mWeaponMultiplier, 1.f);
    EXPECT_FLOAT_EQ(compiled.mSkillMultiplier, 1.8f);
    EXPECT_FLOAT_EQ(compiled.mAttributeBase, .5f);
    EXPECT_FLOAT_EQ(compiled.mAttributeMultiplier, 1.f);
    EXPECT_EQ(compiled.mLuckSkillBase, -20);
    ESM4::GameSetting weapon{}, fatigue{};
    weapon.mEditorId = "fDamageWeaponMult";
    weapon.mData = .5f;
    fatigue.mEditorId = "fFatigueBase";
    fatigue.mData = 1.f;
    const std::array<const ESM4::GameSetting*, 2> settings{ &weapon, &fatigue };
    const auto native = ESM4::buildPhysicalCombatSettings(settings);
    EXPECT_FLOAT_EQ(native.mWeaponMultiplier, .5f);
    EXPECT_FLOAT_EQ(native.mFatigueBase, 1.f);
    EXPECT_FLOAT_EQ(native.mSkillMultiplier, 1.8f);
    weapon.mData = std::int32_t{1};
    EXPECT_THROW(ESM4::buildPhysicalCombatSettings(settings), std::invalid_argument);
    weapon.mData = -1.f;
    EXPECT_THROW(ESM4::buildPhysicalCombatSettings(settings), std::invalid_argument);
    weapon.mData = std::numeric_limits<float>::quiet_NaN();
    EXPECT_THROW(ESM4::buildPhysicalCombatSettings(settings), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, HandToHandDamagesHealthAndFatigueFromNativeRange)
{
    const ESM4::HandToHandSettings settings{0, 1, 0, .75f, 1, 15, 1, .5f};
    auto input = ESM4::HandToHandInput{50, 50, 50, 1.f};
    // 1 + (15-1) * (.5 * .375 * 1) = 3.625; secondary = 1 + .5*3.625.
    auto result = ESM4::handToHandDamage(input, settings, installed);
    EXPECT_FLOAT_EQ(result.mHealth, 3.625f);
    EXPECT_FLOAT_EQ(result.mFatigue, 2.8125f);
    input = {100, 50, 100, 1};
    result = ESM4::handToHandDamage(input, settings, installed);
    EXPECT_FLOAT_EQ(result.mHealth, 11.5f);
    EXPECT_FLOAT_EQ(result.mFatigue, 6.75f);
    input.mStrength = 101;
    EXPECT_FLOAT_EQ(ESM4::handToHandDamage(input, settings, installed).mHealth, 11.5f);
    input = {0, 50, 0, 0};
    result = ESM4::handToHandDamage(input, settings, installed);
    EXPECT_FLOAT_EQ(result.mHealth, 1);
    EXPECT_FLOAT_EQ(result.mFatigue, 1.5f);
    input = {100, 50, 100, 3}; // The pre-range interpolation factor caps at one.
    result = ESM4::handToHandDamage(input, settings, installed);
    EXPECT_FLOAT_EQ(result.mHealth, 15);
    EXPECT_FLOAT_EQ(result.mFatigue, 8.5f);
    input.mSuppressFatigueDamage = true;
    result = ESM4::handToHandDamage(input, settings, installed);
    EXPECT_FLOAT_EQ(result.mHealth, 15);
    EXPECT_FLOAT_EQ(result.mFatigue, 0);
}

TEST(ESM4PhysicalCombat, BlockingUsesEquipmentAndFatigueBeforeMaximum)
{
    const ESM4::BlockSettings settings{0, 1, .75f, .5f, .25f};
    using Equipment = ESM4::BlockEquipment;
    for (auto equipment : {Equipment::Shield, Equipment::Weapon, Equipment::Unarmed})
    {
        const float factor = equipment == Equipment::Shield ? 1.f : equipment == Equipment::Weapon ? .5f : .25f;
        EXPECT_NEAR(ESM4::blockFraction({50, 50, .5f, equipment}, settings, installed), .375f * factor, .000001f);
        EXPECT_FLOAT_EQ(ESM4::blockFraction({0, 50, 1, equipment}, settings, installed), 0);
        EXPECT_NEAR(ESM4::blockFraction({1, 50, 1, equipment}, settings, installed), .01f * factor, .000001f);
    }
    EXPECT_NEAR(ESM4::blockFraction({74, 50, 1, Equipment::Shield}, settings, installed), .74f, .000001f);
    EXPECT_FLOAT_EQ(ESM4::blockFraction({75, 50, 1, Equipment::Shield}, settings, installed), .75f);
    EXPECT_FLOAT_EQ(ESM4::blockFraction({76, 50, 1, Equipment::Shield}, settings, installed), .75f);
    EXPECT_FLOAT_EQ(ESM4::blockFraction({100, 50, 1, Equipment::Weapon}, settings, installed), .5f);
    EXPECT_FLOAT_EQ(ESM4::blockFraction({100, 50, 1, Equipment::Unarmed}, settings, installed), .25f);
}

TEST(ESM4PhysicalCombat, DifficultyAffectsOnlyTheResolvedPlayerSide)
{
    using Role = ESM4::PlayerDamageRole;
    for (float slider : {-1.f, -.5f, 0.f, .5f, 1.f})
    {
        const float incoming = slider == -1 ? 10.f : slider == -.5f ? 60.f / 3.5f
            : slider == 0 ? 60.f : slider == .5f ? 210.f : 360.f;
        const float outgoing = slider == -1 ? 360.f : slider == -.5f ? 210.f
            : slider == 0 ? 60.f : slider == .5f ? 60.f / 3.5f : 10.f;
        EXPECT_NEAR(ESM4::difficultyDamage(60, slider, 5, Role::Victim), incoming, .00002f);
        EXPECT_NEAR(ESM4::difficultyDamage(60, slider, 5, Role::Attacker), outgoing, .00002f);
        EXPECT_FLOAT_EQ(ESM4::difficultyDamage(60, slider, 5, Role::Unaffected), 60);
        EXPECT_FLOAT_EQ(ESM4::difficultyDamage(0, slider, 5, Role::Victim), 0);
    }
    EXPECT_FLOAT_EQ(ESM4::difficultyDamage(1, 1, 5, Role::Victim), 6);
    EXPECT_FLOAT_EQ(ESM4::difficultyDamage(60, 1, 0, Role::Victim), 60);
    for (float tiny : {std::nextafter(0.f, -1.f), std::nextafter(0.f, 1.f)})
        EXPECT_FLOAT_EQ(ESM4::difficultyDamage(60, tiny, 5, Role::Victim), 60);
}

TEST(ESM4PhysicalCombat, HandBlockAndDifficultyRejectInvalidDomains)
{
    ESM4::HandToHandSettings hand{0, 1, 0, .75f, 1, 15, 1, .5f};
    ESM4::BlockSettings block{0, 1, .75f, .5f, .25f};
    const auto shield = ESM4::BlockEquipment::Shield;
    for (float value : {std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN()})
    {
        EXPECT_THROW(ESM4::handToHandDamage({50, 50, 50, value}, hand, installed), std::invalid_argument);
        EXPECT_THROW(ESM4::blockFraction({50, 50, value, shield}, block, installed), std::invalid_argument);
        EXPECT_THROW(ESM4::difficultyDamage(10, value, 5, ESM4::PlayerDamageRole::Victim), std::invalid_argument);
    }
    hand.mHealthMinimum = 16;
    EXPECT_THROW(ESM4::handToHandDamage({50, 50, 50, 1}, hand, installed), std::invalid_argument);
    block.mMaximum = 1.01f;
    EXPECT_THROW(ESM4::blockFraction({50, 50, 1, shield}, block, installed), std::invalid_argument);
    block.mMaximum = .75f;
    EXPECT_THROW(ESM4::blockFraction({50, 50, 1, static_cast<ESM4::BlockEquipment>(99)}, block, installed), std::invalid_argument);
    for (float value : {std::nextafter(-1.f, -2.f), std::nextafter(1.f, 2.f)})
        EXPECT_THROW(ESM4::difficultyDamage(10, value, 5, ESM4::PlayerDamageRole::Victim), std::invalid_argument);
    EXPECT_THROW(ESM4::difficultyDamage(-1, 0, 5, ESM4::PlayerDamageRole::Victim), std::invalid_argument);
    EXPECT_THROW(ESM4::difficultyDamage(1, 0, -1, ESM4::PlayerDamageRole::Victim), std::invalid_argument);
    EXPECT_THROW(ESM4::difficultyDamage(1, 0, 5, static_cast<ESM4::PlayerDamageRole>(99)), std::invalid_argument);
    EXPECT_THROW(ESM4::difficultyDamage(std::numeric_limits<float>::max(), 1, 5,
        ESM4::PlayerDamageRole::Victim), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, NativeHandBlockAndDifficultySettingsUseTypedOverrides)
{
    EXPECT_FLOAT_EQ(ESM4::buildHandToHandSettings({}).mHealthMaximum, 20);
    EXPECT_FLOAT_EQ(ESM4::buildHandToHandSettings({}).mFatigueMultiplier, .25f);
    EXPECT_FLOAT_EQ(ESM4::buildBlockSettings({}).mMaximum, .75f);
    EXPECT_FLOAT_EQ(ESM4::buildDifficultyDamageMultiplier({}), 10);
    ESM4::GameSetting hand{}, block{}, difficulty{};
    hand.mEditorId = "fHandHealthMax";
    hand.mData = 15.f;
    block.mEditorId = "fBlockMax";
    block.mData = .6f;
    difficulty.mEditorId = "fDifficultyDamageMultiplier";
    difficulty.mData = 5.f;
    const std::array<const ESM4::GameSetting*, 3> settings{ &hand, &block, &difficulty };
    EXPECT_FLOAT_EQ(ESM4::buildHandToHandSettings(settings).mHealthMaximum, 15);
    EXPECT_FLOAT_EQ(ESM4::buildBlockSettings(settings).mMaximum, .6f);
    EXPECT_FLOAT_EQ(ESM4::buildDifficultyDamageMultiplier(settings), 5);
    hand.mData = .5f; // Below the compiled minimum.
    EXPECT_THROW(ESM4::buildHandToHandSettings(settings), std::invalid_argument);
    block.mData = 1.1f;
    EXPECT_THROW(ESM4::buildBlockSettings(settings), std::invalid_argument);
    difficulty.mData = -1.f;
    EXPECT_THROW(ESM4::buildDifficultyDamageMultiplier(settings), std::invalid_argument);
    difficulty.mData = std::numeric_limits<float>::quiet_NaN();
    EXPECT_THROW(ESM4::buildDifficultyDamageMultiplier(settings), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, ArmorTruncatesBaseHundredthsAndFloorsBeforeCondition)
{
    const ESM4::ArmorRatingSettings settings{.35f, 1, 0, 1};
    // Native caller truncates 14.99 base to 14. At skill 50, floor(14*.675)=9.
    EXPECT_FLOAT_EQ(ESM4::armorRating({1499, 50, 50, .5f}, settings, installed), 4.5f);
    EXPECT_FLOAT_EQ(ESM4::armorRating({1400, 50, 50, 1.25f}, settings, installed), 11.25f);
    EXPECT_FLOAT_EQ(ESM4::armorRating({1400, 0, 50, 1}, settings, installed), 4);
    EXPECT_FLOAT_EQ(ESM4::armorRating({1400, 100, 50, 1}, settings, installed), 14);
    EXPECT_FLOAT_EQ(ESM4::armorRating({1400, 101, 50, 1}, settings, installed), 14);
    for (std::uint16_t value : {0, 1, 99, 100, 101})
        EXPECT_FLOAT_EQ(ESM4::armorRating({value, 0, 50, 1}, settings, installed), 1);
    EXPECT_FLOAT_EQ(ESM4::armorRating({1400, 100, 50, 0}, settings, installed), 0);
    EXPECT_FLOAT_EQ(ESM4::armorRating({65535, 100, 50, 1}, settings, installed), 655);
    // At skill 50 the multiplier is .675: base 19 floors to 12, 20 floors to 13.
    EXPECT_FLOAT_EQ(ESM4::armorRating({1999, 50, 50, 1}, settings, installed), 12);
    EXPECT_FLOAT_EQ(ESM4::armorRating({2000, 50, 50, 1}, settings, installed), 13);
}

TEST(ESM4PhysicalCombat, ArmorTotalCapIsIndependentOfItemConditionAndCanBeDisabled)
{
    for (float value : {0.f, 1.f, 84.f, std::nextafter(85.f, 0.f), 85.f})
        EXPECT_FLOAT_EQ(ESM4::capArmorRating(value, 85), value);
    for (float value : {std::nextafter(85.f, 100.f), 86.f, 1000.f})
        EXPECT_FLOAT_EQ(ESM4::capArmorRating(value, 85), 85);
    EXPECT_FLOAT_EQ(ESM4::capArmorRating(1000, 0), 1000);
    EXPECT_FLOAT_EQ(ESM4::capArmorRating(1000, 1), 1);
}

TEST(ESM4PhysicalCombat, ArmorSettingsAreTypedAndInvalidInputsFail)
{
    const auto settings = ESM4::buildArmorRatingSettings({});
    EXPECT_FLOAT_EQ(settings.mSkillBase, .35f);
    EXPECT_FLOAT_EQ(settings.mSkillMaximum, 1);
    EXPECT_FLOAT_EQ(settings.mConditionBase, 0);
    EXPECT_FLOAT_EQ(settings.mConditionMultiplier, 1);
    EXPECT_FLOAT_EQ(ESM4::buildMaximumArmorRating({}), 90);
    ESM4::GameSetting maximum{};
    maximum.mEditorId = "fMaxArmorRating";
    maximum.mData = 85.f;
    const std::array<const ESM4::GameSetting*, 1> values{ &maximum };
    EXPECT_FLOAT_EQ(ESM4::buildMaximumArmorRating(values), 85);
    maximum.mData = std::int32_t{85};
    EXPECT_THROW(ESM4::buildMaximumArmorRating(values), std::invalid_argument);
    maximum.mData = -1.f;
    EXPECT_THROW(ESM4::buildMaximumArmorRating(values), std::invalid_argument);
    auto bad = settings;
    bad.mSkillMaximum = .1f;
    EXPECT_THROW(ESM4::armorRating({1400, 50, 50, 1}, bad, installed), std::invalid_argument);
    for (float invalid : {-1.f, std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN()})
    {
        EXPECT_THROW(ESM4::armorRating({1400, 50, 50, invalid}, settings, installed), std::invalid_argument);
        EXPECT_THROW(ESM4::capArmorRating(invalid, 85), std::invalid_argument);
        EXPECT_THROW(ESM4::capArmorRating(85, invalid), std::invalid_argument);
    }
    EXPECT_THROW(ESM4::armorRating({65535, 100, 50, std::numeric_limits<float>::max()}, settings, installed), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, AttackFatigueUsesWeightAndPowerMultiplier)
{
    const ESM4::AttackFatigueSettings settings{7.f, .1f, 5.f};
    // Original 0x547560: R(base + weight*mult), then R(cost*power).
    for (const auto& pair : {std::pair{0.f, 7.f}, {1.f, 7.1f}, {20.f, 9.f}, {100.f, 17.f}, {10000.f, 1007.f}})
    {
        EXPECT_FLOAT_EQ(ESM4::attackFatigueCost(pair.first, false, settings), pair.second);
        EXPECT_FLOAT_EQ(ESM4::attackFatigueCost(pair.first, true, settings), pair.second * 5.f);
    }
    EXPECT_EQ(ESM4::attackFatigueCost(std::nextafter(0.f, 1.f), false, settings), 7.f);
    // A float store occurs before power scaling: halfway above 1 rounds to 1.
    const ESM4::AttackFatigueSettings rounding{1.f, .5f, 2.f};
    EXPECT_EQ(ESM4::attackFatigueCost(std::ldexp(1.f, -23), true, rounding), 2.f);
    EXPECT_EQ(ESM4::attackFatigueCost(100.f, true, {0.f, 0.f, 0.f}), 0.f);
}

TEST(ESM4PhysicalCombat, AttackFatigueRejectsInvalidFactorsAndOverflow)
{
    const ESM4::AttackFatigueSettings settings{7.f, .1f, 5.f};
    for (float invalid : {-1.f, std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN()})
    {
        EXPECT_THROW(ESM4::attackFatigueCost(invalid, false, settings), std::invalid_argument);
        EXPECT_THROW(ESM4::attackFatigueCost(1.f, false, {invalid, .1f, 5.f}), std::invalid_argument);
        EXPECT_THROW(ESM4::attackFatigueCost(1.f, false, {7.f, invalid, 5.f}), std::invalid_argument);
        EXPECT_THROW(ESM4::attackFatigueCost(1.f, false, {7.f, .1f, invalid}), std::invalid_argument);
    }
    EXPECT_THROW(ESM4::attackFatigueCost(std::numeric_limits<float>::max(), true, {1.f, 1.f, 5.f}), std::invalid_argument);
    EXPECT_THROW(ESM4::attackFatigueCost(std::numeric_limits<float>::max(), false, {1.f, 5.f, 1.f}), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, AttackFatigueSettingsUseTypedNativeOverrides)
{
    const auto defaults = ESM4::buildAttackFatigueSettings({});
    EXPECT_FLOAT_EQ(defaults.mBase, 8.f);
    EXPECT_FLOAT_EQ(defaults.mWeightMultiplier, .1f);
    EXPECT_FLOAT_EQ(defaults.mPowerMultiplier, 5.f);
    ESM4::GameSetting base{};
    base.mEditorId = "fFatigueAttackWeaponBase";
    base.mData = 7.f;
    const std::array<const ESM4::GameSetting*, 1> values{&base};
    EXPECT_FLOAT_EQ(ESM4::buildAttackFatigueSettings(values).mBase, 7.f);
    base.mData = std::int32_t{7};
    EXPECT_THROW(ESM4::buildAttackFatigueSettings(values), std::invalid_argument);
    base.mData = -1.f;
    EXPECT_THROW(ESM4::buildAttackFatigueSettings(values), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, CombatMasteryUsesNativeThresholds)
{
    const ESM4::CombatMasterySettings settings{{25, 50, 75, 100}};
    using Rank = ESM4::CombatMastery;
    EXPECT_EQ(ESM4::combatMastery(std::numeric_limits<int>::min(), settings), Rank::Novice);
    EXPECT_EQ(ESM4::combatMastery(0, settings), Rank::Novice);
    EXPECT_EQ(ESM4::combatMastery(1, settings), Rank::Novice);
    for (int tier = 0; tier < 4; ++tier)
    {
        const int threshold = (tier + 1) * 25;
        EXPECT_EQ(ESM4::combatMastery(threshold - 1, settings), static_cast<Rank>(tier));
        EXPECT_EQ(ESM4::combatMastery(threshold, settings), static_cast<Rank>(tier + 1));
        EXPECT_EQ(ESM4::combatMastery(threshold + 1, settings), static_cast<Rank>(tier + 1));
    }
    EXPECT_EQ(ESM4::combatMastery(std::numeric_limits<int>::max(), settings), Rank::Master);
    EXPECT_EQ(ESM4::combatMastery(3, {{1, 2, 3, 4}}), Rank::Expert);
    EXPECT_EQ(ESM4::combatMastery(0, {{0, 0, 0, 0}}), Rank::Master);
}

TEST(ESM4PhysicalCombat, DirectionalPowerMultipliersUnlockIndependently)
{
    const ESM4::CombatMasterySettings mastery{{25, 50, 75, 100}};
    // Deliberately distinct overrides prove selection even though installed
    // side/back/forward settings all happen to equal the novice multiplier.
    const ESM4::PowerAttackSettings settings{2.f, 3.f, 4.f, 5.f, 6.f};
    using Direction = ESM4::PowerAttackDirection;
    struct Case { Direction direction; int threshold; float expected; };
    for (const auto& c : {Case{Direction::Standing, 25, 3.f}, {Direction::Left, 50, 4.f},
             {Direction::Right, 50, 4.f}, {Direction::Backward, 75, 5.f}, {Direction::Forward, 100, 6.f}})
    {
        EXPECT_EQ(ESM4::powerAttackMultiplier(0, c.direction, settings, mastery), 2.f);
        EXPECT_EQ(ESM4::powerAttackMultiplier(c.threshold - 1, c.direction, settings, mastery), 2.f);
        EXPECT_EQ(ESM4::powerAttackMultiplier(c.threshold, c.direction, settings, mastery), c.expected);
        EXPECT_EQ(ESM4::powerAttackMultiplier(c.threshold + 1, c.direction, settings, mastery), c.expected);
        EXPECT_EQ(ESM4::powerAttackMultiplier(1000, c.direction, settings, mastery), c.expected);
    }
    EXPECT_EQ(ESM4::powerAttackMultiplier(100, Direction::Standing, {0, 0, 0, 0, 0}, mastery), 0.f);
}

TEST(ESM4PhysicalCombat, MasteryAndPowerInputsRejectInvalidDomains)
{
    const ESM4::CombatMasterySettings mastery{{25, 50, 75, 100}};
    const ESM4::PowerAttackSettings settings{2.5f, 3.f, 2.5f, 2.5f, 2.5f};
    EXPECT_THROW(ESM4::combatMastery(50, {{-1, 50, 75, 100}}), std::invalid_argument);
    EXPECT_THROW(ESM4::combatMastery(50, {{50, 25, 75, 100}}), std::invalid_argument);
    for (int skill : {0, 100})
        EXPECT_THROW(ESM4::powerAttackMultiplier(skill, static_cast<ESM4::PowerAttackDirection>(99), settings, mastery), std::invalid_argument);
    for (float invalid : {-1.f, std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN()})
        for (float ESM4::PowerAttackSettings::* member : {&ESM4::PowerAttackSettings::mBaseMultiplier,
                 &ESM4::PowerAttackSettings::mStandingMultiplier, &ESM4::PowerAttackSettings::mSideMultiplier,
                 &ESM4::PowerAttackSettings::mBackwardMultiplier, &ESM4::PowerAttackSettings::mForwardMultiplier})
        {
            auto bad = settings;bad.*member = invalid;
            EXPECT_THROW(ESM4::powerAttackMultiplier(0, ESM4::PowerAttackDirection::Standing, bad, mastery), std::invalid_argument);
        }
}

TEST(ESM4PhysicalCombat, MasteryAndPowerSettingsUseNativeTypesAndFallbacks)
{
    EXPECT_EQ(ESM4::buildCombatMasterySettings({}).mMinimumSkill, (std::array<std::int32_t, 4>{25, 50, 75, 100}));
    const auto defaults = ESM4::buildPowerAttackSettings({});
    EXPECT_EQ(defaults.mBaseMultiplier, 3.f);
    EXPECT_EQ(defaults.mStandingMultiplier, 4.f);
    EXPECT_EQ(defaults.mSideMultiplier, 3.f);
    EXPECT_EQ(defaults.mBackwardMultiplier, 3.f);
    EXPECT_EQ(defaults.mForwardMultiplier, 3.f);
    ESM4::GameSetting threshold{}, multiplier{};
    threshold.mEditorId = "iSkillApprenticeMin";threshold.mData = std::int32_t{20};
    multiplier.mEditorId = "fDamagePowerAttackBonus";multiplier.mData = 2.5f;
    const std::array<const ESM4::GameSetting*, 2> values{&threshold, &multiplier};
    EXPECT_EQ(ESM4::buildCombatMasterySettings(values).mMinimumSkill[0], 20);
    EXPECT_EQ(ESM4::buildPowerAttackSettings(values).mBaseMultiplier, 2.5f);
    threshold.mData = 20.f;
    EXPECT_THROW(ESM4::buildCombatMasterySettings(values), std::invalid_argument);
    multiplier.mData = std::int32_t{3};
    EXPECT_THROW(ESM4::buildPowerAttackSettings(values), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, OriginalFirstPunchHealthObservation)
{
    // Original 1.2.0416, M15-S2-ORACLE-HAND-01: ordinary first punch, no
    // equipment/spells on the victim, default difficulty. Console displays
    // victim health 500.00 -> 498.58. Exact contact fatigue was not captured.
    const ESM4::HandToHandSettings hand{0, 1, 0, .75f, 1, 15, 1, .5f};
    const auto full = ESM4::handToHandDamage({10, 50, 40, 1.f}, hand, installed);
    EXPECT_NEAR(500.f - full.mHealth, 498.58f, .0051f);
    // Independently derived lower damage bound if all seven attack fatigue
    // points were still missing at contact: 1 + 14*(.1*.3*.975) = 1.4095.
    const auto depleted = ESM4::handToHandDamage({10, 50, 40, .95f}, hand, installed);
    EXPECT_NEAR(depleted.mHealth, 1.4095f, .00001f);
    EXPECT_LE(depleted.mHealth, full.mHealth);
}

TEST(ESM4PhysicalCombat, OriginalFirstPowerPunchUsesPreDebitFatigue)
{
    // M15-S2-ORACLE-HAND-03: first held attack, 500.00 -> 496.45 health.
    // Original player contact handler runs before this attack's fatigue debit.
    const ESM4::HandToHandSettings hand{0, 1, 0, .75f, 1, 15, 1, .5f};
    const ESM4::CombatMasterySettings mastery{{25, 50, 75, 100}};
    const ESM4::PowerAttackSettings power{2.5f, 3.f, 2.5f, 2.5f, 2.5f};
    const auto damage = ESM4::handToHandDamage({10, 50, 40, 1.f}, hand, installed);
    const float multiplier = ESM4::powerAttackMultiplier(10, ESM4::PowerAttackDirection::Standing, power, mastery);
    EXPECT_NEAR(500.f - damage.mHealth * multiplier, 496.45f, .0051f);
    EXPECT_FLOAT_EQ(ESM4::attackFatigueCost(0, true, {7, .1f, 5}), 35);
    // A wrongly ordered debit produces a distinguishable health result.
    const auto wrongOrder = ESM4::handToHandDamage({10, 50, 40, .75f}, hand, installed);
    EXPECT_GT(500.f - wrongOrder.mHealth * multiplier, 496.57f);
}

TEST(ESM4PhysicalCombat, OriginalFirstSwordHealthObservation)
{
    // M15-S2-ORACLE-WEAPON-01: normal inventory pickup/equip, first ordinary
    // swing, naked victim, neutral difficulty. Original health 500 -> 483.38.
    // Independently predicted 100*.5*1*(.2+.1*1.5)*(.75+.4*.5) = 16.625.
    ESM4::WeaponDamageInput input{10, 50, 40, 100, 1.f, 1.f};
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), 16.625f, .00001f);
    EXPECT_NEAR(500.f - ESM4::weaponDamage(input, installed), 483.38f, .0051f);
    input.mFatigueRatio = .95f; // Incorrectly debit seven fatigue before contact.
    EXPECT_GT(500.f - ESM4::weaponDamage(input, installed), 483.78f);
}

TEST(ESM4PhysicalCombat, WeaponWearUsesBaseDamage)
{
    const ESM4::DurabilitySettings settings{.06f, 9.f};
    for (const auto& c : {std::pair{0, 0.f}, {1, .06f}, {99, 5.94f}, {100, 6.f},
             {101, 6.06f}, {65535, 3932.1f}})
        EXPECT_NEAR(ESM4::weaponWear(c.first, settings), c.second, std::max(.000001f, c.second * 1e-7f));
    EXPECT_EQ(ESM4::weaponWear(65535, {0, 9}), 0);
}

TEST(ESM4PhysicalCombat, ArmorWearUsesAbsorbedDamageWithoutIntermediateRounding)
{
    const ESM4::DurabilitySettings settings{.06f, 9.f};
    for (const auto& c : {std::pair{0.f, 0.f}, {.01f, 9.f}, {.5f, 450.f}, {.85f, 765.f}, {1.f, 900.f}})
        EXPECT_NEAR(ESM4::armorWear(100, c.first, settings), c.second, .0001f);
    EXPECT_EQ(ESM4::armorWear(0, 1, settings), 0);
    EXPECT_EQ(ESM4::armorWear(1, 1, settings), 9);
    EXPECT_EQ(ESM4::armorWear(100, 1, {.06f, 0}), 0);
    const float below = std::nextafter(.5f, 0.f), above = std::nextafter(.5f, 1.f);
    EXPECT_LT(ESM4::armorWear(100, below, settings), 450);
    EXPECT_GT(ESM4::armorWear(100, above, settings), 450);
    // One original x87 store after both products: exact binary operands
    // (1+2^-23)*(1-2^-24)*3 round to 3+2^-22, not 3.
    EXPECT_EQ(ESM4::armorWear(std::nextafter(1.f, 2.f), std::nextafter(1.f, 0.f), {0, 3}),
        std::nextafter(3.f, 4.f));
}

TEST(ESM4PhysicalCombat, DurabilityRejectsInvalidInputsAndOverflow)
{
    const ESM4::DurabilitySettings settings{.06f, 9.f};
    for (float invalid : {-1.f, std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN()})
    {
        EXPECT_THROW(ESM4::weaponWear(1, {invalid, 9}), std::invalid_argument);
        EXPECT_THROW(ESM4::armorWear(1, 1, {.06f, invalid}), std::invalid_argument);
        EXPECT_THROW(ESM4::armorWear(invalid, 1, settings), std::invalid_argument);
        EXPECT_THROW(ESM4::armorWear(1, invalid, settings), std::invalid_argument);
    }
    EXPECT_THROW(ESM4::armorWear(1, std::nextafter(1.f, 2.f), settings), std::invalid_argument);
    EXPECT_THROW(ESM4::weaponWear(65535, {std::numeric_limits<float>::max(), 9}), std::invalid_argument);
    EXPECT_THROW(ESM4::armorWear(std::numeric_limits<float>::max(), 1, settings), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, DurabilitySettingsUseNativeTypesAndDefaults)
{
    const auto defaults = ESM4::buildDurabilitySettings({});
    EXPECT_EQ(defaults.mWeaponDamageMultiplier, .01f);
    EXPECT_EQ(defaults.mArmorDamageMultiplier, .5f);
    ESM4::GameSetting weapon{}, armor{};
    weapon.mEditorId = "fDamageToWeaponPercentage";weapon.mData = .06f;
    armor.mEditorId = "fDamageToArmorPercentage";armor.mData = 9.f;
    const std::array<const ESM4::GameSetting*, 2> values{&weapon, &armor};
    const auto result = ESM4::buildDurabilitySettings(values);
    EXPECT_EQ(result.mWeaponDamageMultiplier, .06f);
    EXPECT_EQ(result.mArmorDamageMultiplier, 9.f);
    weapon.mData = std::int32_t{1};
    EXPECT_THROW(ESM4::buildDurabilitySettings(values), std::invalid_argument);
    weapon.mData = -.01f;
    EXPECT_THROW(ESM4::buildDurabilitySettings(values), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, ArmorMitigationUsesFractionStoreAndBypass)
{
    for (const auto& c : {std::pair{0.f, 100.f}, {1.f, 99.f}, {50.f, 50.f}, {85.f, 15.f},
             {99.f, 1.f}, {100.f, 0.f}, {101.f, 0.f}, {10000.f, 0.f}})
    {
        const auto result = ESM4::mitigateArmor(100, c.first, 1, false);
        EXPECT_NEAR(result.mHealthDamage, c.second, .00001f);
        EXPECT_NEAR(result.mAbsorbedFraction, (100.f - c.second) / 100.f, .000001f);
        EXPECT_EQ(ESM4::mitigateArmor(100, c.first, 1, true).mHealthDamage, 100);
    }
    EXPECT_EQ(ESM4::mitigateArmor(0, 85, 1, false).mHealthDamage, 0);
    EXPECT_NEAR(ESM4::mitigateArmor(1, 85, 1, false).mHealthDamage, .15f, .000001f);
    EXPECT_EQ(ESM4::mitigateArmor(100, 85, .5f, false).mHealthDamage, 50);
    EXPECT_EQ(ESM4::mitigateArmor(100, 85, 0, false).mHealthDamage, 100);
    EXPECT_EQ(ESM4::mitigateArmor(100, 101, 2, false).mHealthDamage, 0);
    EXPECT_GT(ESM4::mitigateArmor(100, std::nextafter(100.f, 0.f), 1, false).mHealthDamage, 0);
    EXPECT_EQ(ESM4::mitigateArmor(100, std::nextafter(100.f, 101.f), 1, false).mHealthDamage, 0);
}

TEST(ESM4PhysicalCombat, PositiveWearSnapsConditionBelowOne)
{
    EXPECT_EQ(ESM4::conditionAfterWear(1000, 6), 994);
    EXPECT_EQ(ESM4::conditionAfterWear(1250, 6), 1244); // Above normal repair preserved.
    EXPECT_EQ(ESM4::conditionAfterWear(0, 0), 0);
    EXPECT_EQ(ESM4::conditionAfterWear(1, 0), 1);
    EXPECT_EQ(ESM4::conditionAfterWear(.5f, 0), .5f); // Original no-wear early return.
    EXPECT_EQ(ESM4::conditionAfterWear(.5f, .01f), 0);
    EXPECT_EQ(ESM4::conditionAfterWear(2, 1), 1);
    EXPECT_GT(ESM4::conditionAfterWear(std::nextafter(2.f, 3.f), 1), 1);
    EXPECT_EQ(ESM4::conditionAfterWear(std::nextafter(2.f, 1.f), 1), 0);
    EXPECT_EQ(ESM4::conditionAfterWear(1, 2), 0);
    EXPECT_EQ(ESM4::conditionAfterWear(1, std::numeric_limits<float>::max()), 0);
}

TEST(ESM4PhysicalCombat, ArmorWearMasteryUsesNoviceAndJourneymanBranches)
{
    const ESM4::CombatMasterySettings mastery{{25, 50, 75, 100}};
    // Distinct factors prove class selection; installed factors share values.
    const ESM4::ArmorWearMasterySettings settings{1.5f, 2.f, .5f, .25f};
    for (int skill : {-1, 0, 1, 24, 25, 26, 49, 50, 51, 74, 75, 76, 99, 100, 101})
    {
        EXPECT_EQ(ESM4::armorWearMasteryMultiplier(skill, ESM4::ArmorWeight::Light, settings, mastery),
            skill < 25 ? 1.5f : skill < 50 ? 1.f : .5f);
        EXPECT_EQ(ESM4::armorWearMasteryMultiplier(skill, ESM4::ArmorWeight::Heavy, settings, mastery),
            skill < 25 ? 2.f : skill < 50 ? 1.f : .25f);
    }
    EXPECT_EQ(ESM4::armorWearMasteryMultiplier(20, ESM4::ArmorWeight::Light, settings, {{10, 20, 30, 40}}), .5f);
}

TEST(ESM4PhysicalCombat, ArmorMutationArithmeticRejectsInvalidDomains)
{
    const ESM4::ArmorWearMasterySettings settings{1.5f, 1.5f, .5f, .5f};
    const ESM4::CombatMasterySettings mastery{{25, 50, 75, 100}};
    for (float bad : {-1.f, std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN()})
    {
        EXPECT_THROW(ESM4::conditionAfterWear(bad, 1), std::invalid_argument);
        EXPECT_THROW(ESM4::conditionAfterWear(1, bad), std::invalid_argument);
        EXPECT_THROW(ESM4::mitigateArmor(bad, 50, 1, false), std::invalid_argument);
        EXPECT_THROW(ESM4::mitigateArmor(1, bad, 1, false), std::invalid_argument);
        EXPECT_THROW(ESM4::mitigateArmor(1, 50, bad, false), std::invalid_argument);
        EXPECT_THROW(ESM4::mitigateArmor(1, bad, 1, true), std::invalid_argument);
        for (float ESM4::ArmorWearMasterySettings::* member : {&ESM4::ArmorWearMasterySettings::mLightNoviceMultiplier,
                 &ESM4::ArmorWearMasterySettings::mHeavyNoviceMultiplier,
                 &ESM4::ArmorWearMasterySettings::mLightJourneymanMultiplier,
                 &ESM4::ArmorWearMasterySettings::mHeavyJourneymanMultiplier})
        {
            auto invalid = settings;invalid.*member = bad;
            EXPECT_THROW(ESM4::armorWearMasteryMultiplier(50, ESM4::ArmorWeight::Light, invalid, mastery), std::invalid_argument);
        }
    }
    EXPECT_THROW(ESM4::armorWearMasteryMultiplier(50, static_cast<ESM4::ArmorWeight>(99), settings, mastery), std::invalid_argument);
    EXPECT_THROW(ESM4::armorWearMasteryMultiplier(50, ESM4::ArmorWeight::Light, settings, {{25, 24, 75, 100}}), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, ArmorWearMasterySettingsUseTypedNativeValues)
{
    const auto defaults = ESM4::buildArmorWearMasterySettings({});
    EXPECT_EQ(defaults.mLightNoviceMultiplier, 1.5f);
    EXPECT_EQ(defaults.mHeavyNoviceMultiplier, 1.5f);
    EXPECT_EQ(defaults.mLightJourneymanMultiplier, .5f);
    EXPECT_EQ(defaults.mHeavyJourneymanMultiplier, .5f);
    ESM4::GameSetting setting{};
    setting.mEditorId = "fPerkLightArmorJourneymanDamageMult";setting.mData = .25f;
    const std::array<const ESM4::GameSetting*, 1> values{&setting};
    EXPECT_EQ(ESM4::buildArmorWearMasterySettings(values).mLightJourneymanMultiplier, .25f);
    setting.mData = std::int32_t{1};
    EXPECT_THROW(ESM4::buildArmorWearMasterySettings(values), std::invalid_argument);
    setting.mData = -.1f;
    EXPECT_THROW(ESM4::buildArmorWearMasterySettings(values), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, ArmorWearSelectionUsesOrderedThresholds)
{
    const ESM4::ArmorWearSelectionSettings settings{10, 25, 15, 10, 10};
    const std::array<bool, 7> all{true, true, true, true, true, true, true};
    using Slot = ESM4::ArmorWearSlot;
    std::array<unsigned, 7> counts{};
    for (unsigned draw = 0; draw < 100; ++draw)
    {
        const auto slot = ESM4::selectArmorWearSlot(draw, all, settings);
        ASSERT_TRUE(slot);
        ++counts[static_cast<unsigned>(*slot)];
        EXPECT_EQ(*slot, draw < 10 ? Slot::Head : draw < 35 ? Slot::UpperBody
            : draw < 50 ? Slot::LowerBody : draw < 60 ? Slot::Hands
            : draw < 70 ? Slot::Feet : Slot::Shield);
    }
    EXPECT_EQ(counts, (std::array<unsigned, 7>{10, 0, 25, 15, 10, 10, 30}));
    EXPECT_EQ(ESM4::selectArmorWearSlot(0, all, {0, 0, 0, 0, 0}), Slot::Shield);
    EXPECT_EQ(ESM4::selectArmorWearSlot(99, all, {100, 100, 100, 100, 100}), Slot::Head);
}

TEST(ESM4PhysicalCombat, ArmorWearSelectionFallsThroughMissingPieces)
{
    const ESM4::ArmorWearSelectionSettings settings{10, 25, 15, 10, 10};
    std::array<bool, 7> available{true, true, true, true, true, true, true};
    using Slot = ESM4::ArmorWearSlot;
    EXPECT_EQ(ESM4::selectArmorWearSlot(0, available, settings), Slot::Head);
    available[0] = false;
    EXPECT_EQ(ESM4::selectArmorWearSlot(0, available, settings), Slot::Hair);
    available[1] = false;
    EXPECT_EQ(ESM4::selectArmorWearSlot(0, available, settings), Slot::UpperBody);
    available[2] = false;
    EXPECT_EQ(ESM4::selectArmorWearSlot(0, available, settings), Slot::LowerBody);
    available[3] = false;
    EXPECT_EQ(ESM4::selectArmorWearSlot(0, available, settings), Slot::Hands);
    available[4] = false;
    EXPECT_EQ(ESM4::selectArmorWearSlot(0, available, settings), Slot::Feet);
    available[5] = false;
    EXPECT_FALSE(ESM4::selectArmorWearSlot(0, available, settings));
    EXPECT_FALSE(ESM4::selectArmorWearSlot(69, available, settings));
    EXPECT_EQ(ESM4::selectArmorWearSlot(70, available, settings), Slot::Shield);
    available[6] = false;
    for (unsigned draw = 0; draw < 100; ++draw)
        EXPECT_FALSE(ESM4::selectArmorWearSlot(draw, available, settings));
    available[0] = true;
    EXPECT_FALSE(ESM4::selectArmorWearSlot(10, available, settings)); // Never wrap backward.
}

TEST(ESM4PhysicalCombat, ArmorWearSelectionFixedSeedDistribution)
{
    // Independent uniform samples; predeclared 700-count tolerance for 100k
    // draws (more than six standard deviations for the largest bucket).
    std::mt19937 random(0x15a4u);
    const ESM4::ArmorWearSelectionSettings settings{10, 25, 15, 10, 10};
    const std::array<bool, 7> all{true, true, true, true, true, true, true};
    std::array<unsigned, 7> counts{};
    for (unsigned i = 0; i < 100000; ++i)
    {
        const auto slot = ESM4::selectArmorWearSlot(random() % 100, all, settings);
        ASSERT_TRUE(slot);
        ++counts[static_cast<unsigned>(*slot)];
    }
    const std::array<unsigned, 7> expected{10000, 0, 25000, 15000, 10000, 10000, 30000};
    for (unsigned i = 0; i < counts.size(); ++i)
        EXPECT_NEAR(counts[i], expected[i], i == 1 ? 0 : 700);
}

TEST(ESM4PhysicalCombat, ArmorWearSelectionRejectsInvalidDrawsAndSettings)
{
    const ESM4::ArmorWearSelectionSettings settings{10, 25, 15, 10, 10};
    const std::array<bool, 7> none{};
    EXPECT_THROW(ESM4::selectArmorWearSlot(100, none, settings), std::invalid_argument);
    EXPECT_THROW(ESM4::selectArmorWearSlot(std::numeric_limits<unsigned>::max(), none, settings), std::invalid_argument);
    for (std::int32_t ESM4::ArmorWearSelectionSettings::* member : {&ESM4::ArmorWearSelectionSettings::mHeadChance,
             &ESM4::ArmorWearSelectionSettings::mUpperBodyChance, &ESM4::ArmorWearSelectionSettings::mLowerBodyChance,
             &ESM4::ArmorWearSelectionSettings::mHandsChance, &ESM4::ArmorWearSelectionSettings::mFeetChance})
        for (int bad : {-1, 101, std::numeric_limits<int>::max()})
        {
            auto invalid = settings;invalid.*member = bad;
            EXPECT_THROW(ESM4::selectArmorWearSlot(0, none, invalid), std::invalid_argument);
        }
}

TEST(ESM4PhysicalCombat, ArmorWearSelectionSettingsUseNativeDefaultsAndTypes)
{
    const auto defaults = ESM4::buildArmorWearSelectionSettings({});
    EXPECT_EQ(defaults.mHeadChance, 10);
    EXPECT_EQ(defaults.mUpperBodyChance, 25);
    EXPECT_EQ(defaults.mLowerBodyChance, 15);
    EXPECT_EQ(defaults.mHandsChance, 10);
    EXPECT_EQ(defaults.mFeetChance, 10);
    ESM4::GameSetting setting{};
    setting.mEditorId = "iArmorDamageHelmChance";setting.mData = std::int32_t{20};
    const std::array<const ESM4::GameSetting*, 1> values{&setting};
    EXPECT_EQ(ESM4::buildArmorWearSelectionSettings(values).mHeadChance, 20);
    setting.mData = 20.f;
    EXPECT_THROW(ESM4::buildArmorWearSelectionSettings(values), std::invalid_argument);
    setting.mData = std::int32_t{-1};
    EXPECT_THROW(ESM4::buildArmorWearSelectionSettings(values), std::invalid_argument);
    // The original routine uses the remaining interval for shield; this
    // similarly named setting is not read by the selection routine.
    setting.mEditorId = "iArmorDamageShieldChance";setting.mData = std::int32_t{0};
    const auto unchanged = ESM4::buildArmorWearSelectionSettings(values);
    EXPECT_EQ(ESM4::selectArmorWearSlot(99, {true, true, true, true, true, true, true}, unchanged),
        ESM4::ArmorWearSlot::Shield);
}

TEST(ESM4PhysicalCombat, CreatureNaturalDamageUsesFatigueThenIntegerTruncation)
{
    struct Case { std::uint16_t base; float fatigue; std::int32_t expected; };
    for (const auto& c : {Case{0, 1, 0}, {1, 1, 1}, {1, 0, 0}, {5, 1, 5}, {5, .95f, 4},
             {10, .95f, 9}, {10, 0, 5}, {65535, 1, 65535}, {65535, .5f, 49151},
             {10, 2, 15}, {10, -1, 0}, {10, -2, -5}})
        EXPECT_EQ(ESM4::creatureNaturalDamage(c.base, c.fatigue, installed), c.expected);
    // Final product is stored as float before integer truncation. A half-ULP
    // fatigue step below full rounds its fatigue factor to 1, retaining 10.
    EXPECT_EQ(ESM4::creatureNaturalDamage(10, std::nextafter(1.f, 0.f), installed), 10);
    const float twoBelow = std::nextafter(std::nextafter(1.f, 0.f), 0.f);
    EXPECT_EQ(ESM4::creatureNaturalDamage(10, twoBelow, installed), 9);
    auto compiled = installed;compiled.mFatigueBase = 1.25f;
    EXPECT_EQ(ESM4::creatureNaturalDamage(10, 1, compiled), 12);
}

TEST(ESM4PhysicalCombat, CreatureNaturalDamageRejectsNonfiniteAndIntegerOverflow)
{
    for (float invalid : {std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN()})
        EXPECT_THROW(ESM4::creatureNaturalDamage(1, invalid, installed), std::invalid_argument);
    EXPECT_THROW(ESM4::creatureNaturalDamage(65535, 100000, installed), std::invalid_argument);
    EXPECT_THROW(ESM4::creatureNaturalDamage(65535, -100000, installed), std::invalid_argument);
    auto settings = installed;settings.mFatigueBase = -1;
    EXPECT_THROW(ESM4::creatureNaturalDamage(1, 1, settings), std::invalid_argument);
    settings = installed;settings.mFatigueBase = 2147483648.f;settings.mFatigueMultiplier = 0;
    EXPECT_THROW(ESM4::creatureNaturalDamage(1, 1, settings), std::invalid_argument);
    settings.mFatigueBase = std::nextafter(2147483648.f, 0.f);
    EXPECT_EQ(ESM4::creatureNaturalDamage(1, 1, settings), 2147483520);
}

TEST(ESM4PhysicalCombat, KnockdownUsesInclusivePercentileAndFloatThreshold)
{
    const ESM4::KnockdownSettings settings{0, 1, 0, 1, 1};
    struct Case { int agility; int luck; float fatigue; int successes; };
    for (const auto& c : {Case{40, 50, 1, 26}, {40, 50, 0, 51}, {40, 100, 1, 17},
             {100, 50, 1, 11}, {200, 50, 1, 11}, {0, 50, 1, 100}})
    {
        SCOPED_TRACE(c.agility);
        for (unsigned draw = 0; draw != 100; ++draw)
            EXPECT_EQ(ESM4::damageKnockdown(c.agility, c.luck, c.fatigue, 10, draw, settings, installed),
                draw < static_cast<unsigned>(c.successes));
    }
    auto capped = settings;capped.mMaximumChance = .25f;
    EXPECT_TRUE(ESM4::damageKnockdown(1, 50, 1, 100, 25, capped, installed));
    EXPECT_FALSE(ESM4::damageKnockdown(1, 50, 1, 100, 26, capped, installed));
    capped.mMaximumChance = std::nextafter(.25f, 0.f);
    EXPECT_FALSE(ESM4::damageKnockdown(1, 50, 1, 100, 25, capped, installed));
    // Installed .3 * 10 stores exactly 3, then 3/50 rounds below .06.
    const ESM4::KnockdownSettings native{0, 1, 0, .3f, .3f};
    EXPECT_TRUE(ESM4::damageKnockdown(50, 50, 1, 10, 5, native, installed));
    EXPECT_FALSE(ESM4::damageKnockdown(50, 50, 1, 10, 6, native, installed));
}

TEST(ESM4PhysicalCombat, KnockdownPreservesSignedFactorsAndZeroDenominator)
{
    ESM4::KnockdownSettings settings{0, 1, 0, -3, .25f};
    EXPECT_FALSE(ESM4::damageKnockdown(50, 50, 1, 10, 0, settings, installed));
    EXPECT_TRUE(ESM4::damageKnockdown(50, 50, 1, -10, 25, settings, installed));
    settings.mDamageMultiplier = 1;
    EXPECT_TRUE(ESM4::damageKnockdown(0, 50, 1, 10, 25, settings, installed));
    EXPECT_FALSE(ESM4::damageKnockdown(0, 50, 1, 0, 0, settings, installed)); // unordered 0/0
    EXPECT_FALSE(ESM4::damageKnockdown(0, 50, 1, -10, 0, settings, installed));
    EXPECT_TRUE(ESM4::damageKnockdown(50, 50, 1, 0, 0, settings, installed)); // draw <= 0
    EXPECT_FALSE(ESM4::damageKnockdown(50, 50, 1, 0, 1, settings, installed));
    settings.mAgilityBase = 10;settings.mAgilityMultiplier = 0;settings.mDamageBase = 2.5f;
    EXPECT_TRUE(ESM4::damageKnockdown(0, 0, 0, 0, 25, settings, installed));
    EXPECT_FALSE(ESM4::damageKnockdown(0, 0, 0, 0, 26, settings, installed));
}

TEST(ESM4PhysicalCombat, KnockdownSettingsAndInputsAreValidated)
{
    const ESM4::KnockdownSettings settings{0, 1, 0, .3f, .3f};
    for (float bad : {std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN()})
    {
        EXPECT_THROW(ESM4::damageKnockdown(50, 50, bad, 10, 0, settings, installed), std::invalid_argument);
        for (float ESM4::KnockdownSettings::* member : {&ESM4::KnockdownSettings::mAgilityBase,
                 &ESM4::KnockdownSettings::mAgilityMultiplier, &ESM4::KnockdownSettings::mDamageBase,
                 &ESM4::KnockdownSettings::mDamageMultiplier, &ESM4::KnockdownSettings::mMaximumChance})
        {
            auto invalid = settings;invalid.*member = bad;
            EXPECT_THROW(ESM4::validateKnockdownSettings(invalid), std::invalid_argument);
        }
    }
    for (float bad : {-1.f, std::nextafter(1.f, 2.f)})
    {
        auto invalid = settings;invalid.mMaximumChance = bad;
        EXPECT_THROW(ESM4::damageKnockdown(50, 50, 1, 10, 0, invalid, installed), std::invalid_argument);
    }
    EXPECT_THROW(ESM4::damageKnockdown(50, 50, 1, 10, 100, settings, installed), std::invalid_argument);
    auto huge = settings;huge.mDamageMultiplier = std::numeric_limits<float>::max();
    EXPECT_THROW(ESM4::damageKnockdown(50, 50, 1, 10, 0, huge, installed), std::invalid_argument);
    const auto defaults = ESM4::buildKnockdownSettings({});
    EXPECT_EQ(defaults.mAgilityBase, 0);EXPECT_EQ(defaults.mAgilityMultiplier, 1);
    EXPECT_EQ(defaults.mDamageBase, 0);EXPECT_EQ(defaults.mDamageMultiplier, -3);
    EXPECT_EQ(defaults.mMaximumChance, .25f);
    ESM4::GameSetting value{};value.mEditorId = "fKnockdownDamageMult";value.mData = .3f;
    const std::array<const ESM4::GameSetting*, 1> values{&value};
    EXPECT_EQ(ESM4::buildKnockdownSettings(values).mDamageMultiplier, .3f);
    value.mData = std::int32_t{1};
    EXPECT_THROW(ESM4::buildKnockdownSettings(values), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, KnockdownFixedSeedDistributionMatchesInclusiveDraws)
{
    std::mt19937 random(0x4d1531);
    const ESM4::KnockdownSettings settings{0, 1, 0, 1, .25f};
    unsigned successes = 0;
    for (unsigned i = 0; i < 100000; ++i)
        successes += ESM4::damageKnockdown(1, 50, 1, 100, random() % 100, settings, installed);
    // Inclusive 0..25, independently declared 26%, conservative fixed tolerance.
    EXPECT_NEAR(successes, 26000, 700);
}
