#include <components/esm4/physicalcombat.hpp>
#include <components/esm4/combatsettings.hpp>
#include <components/esm4/loadgmst.hpp>
#include <array>
#include <utility>
#include <gtest/gtest.h>
#include <cmath>
#include <limits>

namespace
{
    // Independently decoded installed settings plus verified absent initializers.
    // See M15-NATIVE-RULE-PROVENANCE.md; never generated by production helpers.
    const ESM4::PhysicalCombatSettings installed{ -20, .4f, 1.f, .5f, .5f, .2f, 1.5f, .5f, .5f, .75f, .5f };
}

TEST(ESM4PhysicalCombat, LuckAdjustedSkillClampsAfterAdjustment)
{
    struct Case { int skill; int luck; float expected; };
    for (const auto& c : {Case{0, 50, 0}, {1, 50, 1}, {50, 50, 50}, {100, 50, 100},
             {101, 50, 100}, {50, 0, 30}, {50, 100, 70}, {0, 0, 0},
             {19, 0, 0}, {20, 0, 0}, {21, 0, 1}, {79, 100, 99}, {80, 100, 100},
             {81, 100, 100}, {-100, 50, 0}, {1000, 1000, 100}})
        EXPECT_FLOAT_EQ(ESM4::effectiveCombatSkill(c.skill, c.luck, installed), c.expected);
    EXPECT_NEAR(ESM4::effectiveCombatSkill(50, 49, installed), 49.6f, 0.00001f);
    EXPECT_NEAR(ESM4::effectiveCombatSkill(50, 51, installed), 50.4f, 0.00001f);
}

TEST(ESM4PhysicalCombat, FatigueUsesNativeSettingsWithoutRatioClamping)
{
    for (const auto& pair : {std::pair{-1.f, 0.f}, {0.f, .5f}, {.5f, .75f}, {1.f, 1.f}, {2.f, 1.5f}})
        EXPECT_FLOAT_EQ(ESM4::combatFatigueMultiplier(pair.first, installed), pair.second);
    const float below = std::nextafter(1.f, 0.f), above = std::nextafter(1.f, 2.f);
    EXPECT_LE(ESM4::combatFatigueMultiplier(below, installed), 1.f);
    // Half of one float ULP rounds back to even 1; the next ratio does not.
    EXPECT_EQ(ESM4::combatFatigueMultiplier(above, installed), 1.f);
    EXPECT_GT(ESM4::combatFatigueMultiplier(std::nextafter(above, 2.f), installed), 1.f);
    auto compiled = installed;
    compiled.mFatigueBase = 1.25f;
    EXPECT_FLOAT_EQ(ESM4::combatFatigueMultiplier(1.f, compiled), 1.25f);
}

TEST(ESM4PhysicalCombat, WeaponTermsPreserveRepairedConditionAndAttributeCap)
{
    ESM4::WeaponDamageInput input{50, 50, 50, 100, .5f, .5f};
    // 100*.5 * (.5+.5*.5) * (.2+1.5*.5) * (.75+.5*.5) * (.5+.5*.5).
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), 26.71875f, .00001f);
    input.mAttackMultiplier = 2;
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), 53.4375f, .00002f);
    input = {100, 50, 100, 100, 1.25f, 1.f};
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), 119.53125f, .00003f);
    for (int attribute : {99, 100, 101, 1000})
    {
        input.mAttribute = attribute;
        EXPECT_NEAR(ESM4::weaponDamage(input, installed), attribute == 99 ? 119.053125f : 119.53125f, .00003f);
    }
    input = {0, 50, 0, 100, 0.f, 0.f};
    EXPECT_FLOAT_EQ(ESM4::weaponDamage(input, installed), 1.875f);
    input.mIgnoreFatigue = true;
    EXPECT_FLOAT_EQ(ESM4::weaponDamage(input, installed), 3.75f);
    input.mBaseDamage = 0;
    EXPECT_FLOAT_EQ(ESM4::weaponDamage(input, installed), 0.f);
    input.mBaseDamage = 1;
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), .0375f, .000001f);
    input.mBaseDamage = 65535;
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), 2457.5625f, .001f);
    input.mAttackMultiplier = 0;
    EXPECT_FLOAT_EQ(ESM4::weaponDamage(input, installed), 0.f);
}

TEST(ESM4PhysicalCombat, InvalidInputsAndOverflowNeverBecomeDamage)
{
    ESM4::WeaponDamageInput input{50, 50, 50, 100, 1.f, 1.f};
    for (float value : {std::numeric_limits<float>::quiet_NaN(), std::numeric_limits<float>::infinity(),
             -std::numeric_limits<float>::infinity()})
    {
        auto bad = input;
        bad.mFatigueRatio = value;
        EXPECT_THROW(ESM4::weaponDamage(bad, installed), std::invalid_argument);
        bad = input;
        bad.mConditionRatio = value;
        EXPECT_THROW(ESM4::weaponDamage(bad, installed), std::invalid_argument);
        EXPECT_THROW(ESM4::combatFatigueMultiplier(value, installed), std::invalid_argument);
        auto settings = installed;
        settings.mLuckSkillMultiplier = value;
        EXPECT_THROW(ESM4::effectiveCombatSkill(50, 50, settings), std::invalid_argument);
    }
    input.mConditionRatio = -1;
    EXPECT_THROW(ESM4::weaponDamage(input, installed), std::invalid_argument);
    input.mConditionRatio = 1;
    input.mAttribute = -1;
    EXPECT_THROW(ESM4::weaponDamage(input, installed), std::invalid_argument);
    input.mAttribute = 50;
    input.mAttackMultiplier = -1;
    EXPECT_THROW(ESM4::weaponDamage(input, installed), std::invalid_argument);
    input.mAttackMultiplier = std::numeric_limits<float>::max();
    EXPECT_THROW(ESM4::weaponDamage(input, installed), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, NativeSettingsOverrideCompiledPhysicalDefaults)
{
    const auto compiled = ESM4::buildPhysicalCombatSettings({});
    EXPECT_FLOAT_EQ(compiled.mFatigueBase, 1.25f);
    EXPECT_FLOAT_EQ(compiled.mWeaponMultiplier, 1.f);
    EXPECT_FLOAT_EQ(compiled.mSkillMultiplier, 1.8f);
    EXPECT_FLOAT_EQ(compiled.mAttributeBase, .5f);
    EXPECT_FLOAT_EQ(compiled.mAttributeMultiplier, 1.f);
    EXPECT_EQ(compiled.mLuckSkillBase, -20);
    ESM4::GameSetting weapon{}, fatigue{};
    weapon.mEditorId = "fDamageWeaponMult";
    weapon.mData = .5f;
    fatigue.mEditorId = "fFatigueBase";
    fatigue.mData = 1.f;
    const std::array<const ESM4::GameSetting*, 2> settings{ &weapon, &fatigue };
    const auto native = ESM4::buildPhysicalCombatSettings(settings);
    EXPECT_FLOAT_EQ(native.mWeaponMultiplier, .5f);
    EXPECT_FLOAT_EQ(native.mFatigueBase, 1.f);
    EXPECT_FLOAT_EQ(native.mSkillMultiplier, 1.8f);
    weapon.mData = std::int32_t{1};
    EXPECT_THROW(ESM4::buildPhysicalCombatSettings(settings), std::invalid_argument);
    weapon.mData = -1.f;
    EXPECT_THROW(ESM4::buildPhysicalCombatSettings(settings), std::invalid_argument);
    weapon.mData = std::numeric_limits<float>::quiet_NaN();
    EXPECT_THROW(ESM4::buildPhysicalCombatSettings(settings), std::invalid_argument);
}
