#include <components/esm4/physicalcombat.hpp>
#include <components/esm4/combatsettings.hpp>
#include <components/esm4/loadgmst.hpp>
#include <array>
#include <utility>
#include <gtest/gtest.h>
#include <cmath>
#include <limits>

namespace
{
    // Independently decoded installed settings plus verified absent initializers.
    // See M15-NATIVE-RULE-PROVENANCE.md; never generated by production helpers.
    const ESM4::PhysicalCombatSettings installed{ -20, .4f, 1.f, .5f, .5f, .2f, 1.5f, .5f, .5f, .75f, .5f };
}

TEST(ESM4PhysicalCombat, LuckAdjustedSkillClampsAfterAdjustment)
{
    struct Case { int skill; int luck; float expected; };
    for (const auto& c : {Case{0, 50, 0}, {1, 50, 1}, {50, 50, 50}, {100, 50, 100},
             {101, 50, 100}, {50, 0, 30}, {50, 100, 70}, {0, 0, 0},
             {19, 0, 0}, {20, 0, 0}, {21, 0, 1}, {79, 100, 99}, {80, 100, 100},
             {81, 100, 100}, {-100, 50, 0}, {1000, 1000, 100}})
        EXPECT_FLOAT_EQ(ESM4::effectiveCombatSkill(c.skill, c.luck, installed), c.expected);
    EXPECT_NEAR(ESM4::effectiveCombatSkill(50, 49, installed), 49.6f, 0.00001f);
    EXPECT_NEAR(ESM4::effectiveCombatSkill(50, 51, installed), 50.4f, 0.00001f);
}

TEST(ESM4PhysicalCombat, FatigueUsesNativeSettingsWithoutRatioClamping)
{
    for (const auto& pair : {std::pair{-1.f, 0.f}, {0.f, .5f}, {.5f, .75f}, {1.f, 1.f}, {2.f, 1.5f}})
        EXPECT_FLOAT_EQ(ESM4::combatFatigueMultiplier(pair.first, installed), pair.second);
    const float below = std::nextafter(1.f, 0.f), above = std::nextafter(1.f, 2.f);
    EXPECT_LE(ESM4::combatFatigueMultiplier(below, installed), 1.f);
    // Half of one float ULP rounds back to even 1; the next ratio does not.
    EXPECT_EQ(ESM4::combatFatigueMultiplier(above, installed), 1.f);
    EXPECT_GT(ESM4::combatFatigueMultiplier(std::nextafter(above, 2.f), installed), 1.f);
    auto compiled = installed;
    compiled.mFatigueBase = 1.25f;
    EXPECT_FLOAT_EQ(ESM4::combatFatigueMultiplier(1.f, compiled), 1.25f);
}

TEST(ESM4PhysicalCombat, WeaponTermsPreserveRepairedConditionAndAttributeCap)
{
    ESM4::WeaponDamageInput input{50, 50, 50, 100, .5f, .5f};
    // 100*.5 * (.5+.5*.5) * (.2+1.5*.5) * (.75+.5*.5) * (.5+.5*.5).
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), 26.71875f, .00001f);
    input.mAttackMultiplier = 2;
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), 53.4375f, .00002f);
    input = {100, 50, 100, 100, 1.25f, 1.f};
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), 119.53125f, .00003f);
    for (int attribute : {99, 100, 101, 1000})
    {
        input.mAttribute = attribute;
        EXPECT_NEAR(ESM4::weaponDamage(input, installed), attribute == 99 ? 119.053125f : 119.53125f, .00003f);
    }
    input = {0, 50, 0, 100, 0.f, 0.f};
    EXPECT_FLOAT_EQ(ESM4::weaponDamage(input, installed), 1.875f);
    input.mIgnoreFatigue = true;
    EXPECT_FLOAT_EQ(ESM4::weaponDamage(input, installed), 3.75f);
    input.mBaseDamage = 0;
    EXPECT_FLOAT_EQ(ESM4::weaponDamage(input, installed), 0.f);
    input.mBaseDamage = 1;
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), .0375f, .000001f);
    input.mBaseDamage = 65535;
    EXPECT_NEAR(ESM4::weaponDamage(input, installed), 2457.5625f, .001f);
    input.mAttackMultiplier = 0;
    EXPECT_FLOAT_EQ(ESM4::weaponDamage(input, installed), 0.f);
}

TEST(ESM4PhysicalCombat, InvalidInputsAndOverflowNeverBecomeDamage)
{
    ESM4::WeaponDamageInput input{50, 50, 50, 100, 1.f, 1.f};
    for (float value : {std::numeric_limits<float>::quiet_NaN(), std::numeric_limits<float>::infinity(),
             -std::numeric_limits<float>::infinity()})
    {
        auto bad = input;
        bad.mFatigueRatio = value;
        EXPECT_THROW(ESM4::weaponDamage(bad, installed), std::invalid_argument);
        bad = input;
        bad.mConditionRatio = value;
        EXPECT_THROW(ESM4::weaponDamage(bad, installed), std::invalid_argument);
        EXPECT_THROW(ESM4::combatFatigueMultiplier(value, installed), std::invalid_argument);
        auto settings = installed;
        settings.mLuckSkillMultiplier = value;
        EXPECT_THROW(ESM4::effectiveCombatSkill(50, 50, settings), std::invalid_argument);
    }
    input.mConditionRatio = -1;
    EXPECT_THROW(ESM4::weaponDamage(input, installed), std::invalid_argument);
    input.mConditionRatio = 1;
    input.mAttribute = -1;
    EXPECT_THROW(ESM4::weaponDamage(input, installed), std::invalid_argument);
    input.mAttribute = 50;
    input.mAttackMultiplier = -1;
    EXPECT_THROW(ESM4::weaponDamage(input, installed), std::invalid_argument);
    input.mAttackMultiplier = std::numeric_limits<float>::max();
    EXPECT_THROW(ESM4::weaponDamage(input, installed), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, NativeSettingsOverrideCompiledPhysicalDefaults)
{
    const auto compiled = ESM4::buildPhysicalCombatSettings({});
    EXPECT_FLOAT_EQ(compiled.mFatigueBase, 1.25f);
    EXPECT_FLOAT_EQ(compiled.mWeaponMultiplier, 1.f);
    EXPECT_FLOAT_EQ(compiled.mSkillMultiplier, 1.8f);
    EXPECT_FLOAT_EQ(compiled.mAttributeBase, .5f);
    EXPECT_FLOAT_EQ(compiled.mAttributeMultiplier, 1.f);
    EXPECT_EQ(compiled.mLuckSkillBase, -20);
    ESM4::GameSetting weapon{}, fatigue{};
    weapon.mEditorId = "fDamageWeaponMult";
    weapon.mData = .5f;
    fatigue.mEditorId = "fFatigueBase";
    fatigue.mData = 1.f;
    const std::array<const ESM4::GameSetting*, 2> settings{ &weapon, &fatigue };
    const auto native = ESM4::buildPhysicalCombatSettings(settings);
    EXPECT_FLOAT_EQ(native.mWeaponMultiplier, .5f);
    EXPECT_FLOAT_EQ(native.mFatigueBase, 1.f);
    EXPECT_FLOAT_EQ(native.mSkillMultiplier, 1.8f);
    weapon.mData = std::int32_t{1};
    EXPECT_THROW(ESM4::buildPhysicalCombatSettings(settings), std::invalid_argument);
    weapon.mData = -1.f;
    EXPECT_THROW(ESM4::buildPhysicalCombatSettings(settings), std::invalid_argument);
    weapon.mData = std::numeric_limits<float>::quiet_NaN();
    EXPECT_THROW(ESM4::buildPhysicalCombatSettings(settings), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, HandToHandDamagesHealthAndFatigueFromNativeRange)
{
    const ESM4::HandToHandSettings settings{0, 1, 0, .75f, 1, 15, 1, .5f};
    auto input = ESM4::HandToHandInput{50, 50, 50, 1.f};
    // 1 + (15-1) * (.5 * .375 * 1) = 3.625; secondary = 1 + .5*3.625.
    auto result = ESM4::handToHandDamage(input, settings, installed);
    EXPECT_FLOAT_EQ(result.mHealth, 3.625f);
    EXPECT_FLOAT_EQ(result.mFatigue, 2.8125f);
    input = {100, 50, 100, 1};
    result = ESM4::handToHandDamage(input, settings, installed);
    EXPECT_FLOAT_EQ(result.mHealth, 11.5f);
    EXPECT_FLOAT_EQ(result.mFatigue, 6.75f);
    input.mStrength = 101;
    EXPECT_FLOAT_EQ(ESM4::handToHandDamage(input, settings, installed).mHealth, 11.5f);
    input = {0, 50, 0, 0};
    result = ESM4::handToHandDamage(input, settings, installed);
    EXPECT_FLOAT_EQ(result.mHealth, 1);
    EXPECT_FLOAT_EQ(result.mFatigue, 1.5f);
    input = {100, 50, 100, 3}; // The pre-range interpolation factor caps at one.
    result = ESM4::handToHandDamage(input, settings, installed);
    EXPECT_FLOAT_EQ(result.mHealth, 15);
    EXPECT_FLOAT_EQ(result.mFatigue, 8.5f);
    input.mSuppressFatigueDamage = true;
    result = ESM4::handToHandDamage(input, settings, installed);
    EXPECT_FLOAT_EQ(result.mHealth, 15);
    EXPECT_FLOAT_EQ(result.mFatigue, 0);
}

TEST(ESM4PhysicalCombat, BlockingUsesEquipmentAndFatigueBeforeMaximum)
{
    const ESM4::BlockSettings settings{0, 1, .75f, .5f, .25f};
    using Equipment = ESM4::BlockEquipment;
    for (auto equipment : {Equipment::Shield, Equipment::Weapon, Equipment::Unarmed})
    {
        const float factor = equipment == Equipment::Shield ? 1.f : equipment == Equipment::Weapon ? .5f : .25f;
        EXPECT_NEAR(ESM4::blockFraction({50, 50, .5f, equipment}, settings, installed), .375f * factor, .000001f);
        EXPECT_FLOAT_EQ(ESM4::blockFraction({0, 50, 1, equipment}, settings, installed), 0);
        EXPECT_NEAR(ESM4::blockFraction({1, 50, 1, equipment}, settings, installed), .01f * factor, .000001f);
    }
    EXPECT_NEAR(ESM4::blockFraction({74, 50, 1, Equipment::Shield}, settings, installed), .74f, .000001f);
    EXPECT_FLOAT_EQ(ESM4::blockFraction({75, 50, 1, Equipment::Shield}, settings, installed), .75f);
    EXPECT_FLOAT_EQ(ESM4::blockFraction({76, 50, 1, Equipment::Shield}, settings, installed), .75f);
    EXPECT_FLOAT_EQ(ESM4::blockFraction({100, 50, 1, Equipment::Weapon}, settings, installed), .5f);
    EXPECT_FLOAT_EQ(ESM4::blockFraction({100, 50, 1, Equipment::Unarmed}, settings, installed), .25f);
}

TEST(ESM4PhysicalCombat, DifficultyAffectsOnlyTheResolvedPlayerSide)
{
    using Role = ESM4::PlayerDamageRole;
    for (float slider : {-1.f, -.5f, 0.f, .5f, 1.f})
    {
        const float incoming = slider == -1 ? 10.f : slider == -.5f ? 60.f / 3.5f
            : slider == 0 ? 60.f : slider == .5f ? 210.f : 360.f;
        const float outgoing = slider == -1 ? 360.f : slider == -.5f ? 210.f
            : slider == 0 ? 60.f : slider == .5f ? 60.f / 3.5f : 10.f;
        EXPECT_NEAR(ESM4::difficultyDamage(60, slider, 5, Role::Victim), incoming, .00002f);
        EXPECT_NEAR(ESM4::difficultyDamage(60, slider, 5, Role::Attacker), outgoing, .00002f);
        EXPECT_FLOAT_EQ(ESM4::difficultyDamage(60, slider, 5, Role::Unaffected), 60);
        EXPECT_FLOAT_EQ(ESM4::difficultyDamage(0, slider, 5, Role::Victim), 0);
    }
    EXPECT_FLOAT_EQ(ESM4::difficultyDamage(1, 1, 5, Role::Victim), 6);
    EXPECT_FLOAT_EQ(ESM4::difficultyDamage(60, 1, 0, Role::Victim), 60);
    for (float tiny : {std::nextafter(0.f, -1.f), std::nextafter(0.f, 1.f)})
        EXPECT_FLOAT_EQ(ESM4::difficultyDamage(60, tiny, 5, Role::Victim), 60);
}

TEST(ESM4PhysicalCombat, HandBlockAndDifficultyRejectInvalidDomains)
{
    ESM4::HandToHandSettings hand{0, 1, 0, .75f, 1, 15, 1, .5f};
    ESM4::BlockSettings block{0, 1, .75f, .5f, .25f};
    const auto shield = ESM4::BlockEquipment::Shield;
    for (float value : {std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN()})
    {
        EXPECT_THROW(ESM4::handToHandDamage({50, 50, 50, value}, hand, installed), std::invalid_argument);
        EXPECT_THROW(ESM4::blockFraction({50, 50, value, shield}, block, installed), std::invalid_argument);
        EXPECT_THROW(ESM4::difficultyDamage(10, value, 5, ESM4::PlayerDamageRole::Victim), std::invalid_argument);
    }
    hand.mHealthMinimum = 16;
    EXPECT_THROW(ESM4::handToHandDamage({50, 50, 50, 1}, hand, installed), std::invalid_argument);
    block.mMaximum = 1.01f;
    EXPECT_THROW(ESM4::blockFraction({50, 50, 1, shield}, block, installed), std::invalid_argument);
    block.mMaximum = .75f;
    EXPECT_THROW(ESM4::blockFraction({50, 50, 1, static_cast<ESM4::BlockEquipment>(99)}, block, installed), std::invalid_argument);
    for (float value : {std::nextafter(-1.f, -2.f), std::nextafter(1.f, 2.f)})
        EXPECT_THROW(ESM4::difficultyDamage(10, value, 5, ESM4::PlayerDamageRole::Victim), std::invalid_argument);
    EXPECT_THROW(ESM4::difficultyDamage(-1, 0, 5, ESM4::PlayerDamageRole::Victim), std::invalid_argument);
    EXPECT_THROW(ESM4::difficultyDamage(1, 0, -1, ESM4::PlayerDamageRole::Victim), std::invalid_argument);
    EXPECT_THROW(ESM4::difficultyDamage(1, 0, 5, static_cast<ESM4::PlayerDamageRole>(99)), std::invalid_argument);
    EXPECT_THROW(ESM4::difficultyDamage(std::numeric_limits<float>::max(), 1, 5,
        ESM4::PlayerDamageRole::Victim), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, NativeHandBlockAndDifficultySettingsUseTypedOverrides)
{
    EXPECT_FLOAT_EQ(ESM4::buildHandToHandSettings({}).mHealthMaximum, 20);
    EXPECT_FLOAT_EQ(ESM4::buildHandToHandSettings({}).mFatigueMultiplier, .25f);
    EXPECT_FLOAT_EQ(ESM4::buildBlockSettings({}).mMaximum, .75f);
    EXPECT_FLOAT_EQ(ESM4::buildDifficultyDamageMultiplier({}), 10);
    ESM4::GameSetting hand{}, block{}, difficulty{};
    hand.mEditorId = "fHandHealthMax";
    hand.mData = 15.f;
    block.mEditorId = "fBlockMax";
    block.mData = .6f;
    difficulty.mEditorId = "fDifficultyDamageMultiplier";
    difficulty.mData = 5.f;
    const std::array<const ESM4::GameSetting*, 3> settings{ &hand, &block, &difficulty };
    EXPECT_FLOAT_EQ(ESM4::buildHandToHandSettings(settings).mHealthMaximum, 15);
    EXPECT_FLOAT_EQ(ESM4::buildBlockSettings(settings).mMaximum, .6f);
    EXPECT_FLOAT_EQ(ESM4::buildDifficultyDamageMultiplier(settings), 5);
    hand.mData = .5f; // Below the compiled minimum.
    EXPECT_THROW(ESM4::buildHandToHandSettings(settings), std::invalid_argument);
    block.mData = 1.1f;
    EXPECT_THROW(ESM4::buildBlockSettings(settings), std::invalid_argument);
    difficulty.mData = -1.f;
    EXPECT_THROW(ESM4::buildDifficultyDamageMultiplier(settings), std::invalid_argument);
    difficulty.mData = std::numeric_limits<float>::quiet_NaN();
    EXPECT_THROW(ESM4::buildDifficultyDamageMultiplier(settings), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, ArmorTruncatesBaseHundredthsAndFloorsBeforeCondition)
{
    const ESM4::ArmorRatingSettings settings{.35f, 1, 0, 1};
    // Native caller truncates 14.99 base to 14. At skill 50, floor(14*.675)=9.
    EXPECT_FLOAT_EQ(ESM4::armorRating({1499, 50, 50, .5f}, settings, installed), 4.5f);
    EXPECT_FLOAT_EQ(ESM4::armorRating({1400, 50, 50, 1.25f}, settings, installed), 11.25f);
    EXPECT_FLOAT_EQ(ESM4::armorRating({1400, 0, 50, 1}, settings, installed), 4);
    EXPECT_FLOAT_EQ(ESM4::armorRating({1400, 100, 50, 1}, settings, installed), 14);
    EXPECT_FLOAT_EQ(ESM4::armorRating({1400, 101, 50, 1}, settings, installed), 14);
    for (std::uint16_t value : {0, 1, 99, 100, 101})
        EXPECT_FLOAT_EQ(ESM4::armorRating({value, 0, 50, 1}, settings, installed), 1);
    EXPECT_FLOAT_EQ(ESM4::armorRating({1400, 100, 50, 0}, settings, installed), 0);
    EXPECT_FLOAT_EQ(ESM4::armorRating({65535, 100, 50, 1}, settings, installed), 655);
    // At skill 50 the multiplier is .675: base 19 floors to 12, 20 floors to 13.
    EXPECT_FLOAT_EQ(ESM4::armorRating({1999, 50, 50, 1}, settings, installed), 12);
    EXPECT_FLOAT_EQ(ESM4::armorRating({2000, 50, 50, 1}, settings, installed), 13);
}

TEST(ESM4PhysicalCombat, ArmorTotalCapIsIndependentOfItemConditionAndCanBeDisabled)
{
    for (float value : {0.f, 1.f, 84.f, std::nextafter(85.f, 0.f), 85.f})
        EXPECT_FLOAT_EQ(ESM4::capArmorRating(value, 85), value);
    for (float value : {std::nextafter(85.f, 100.f), 86.f, 1000.f})
        EXPECT_FLOAT_EQ(ESM4::capArmorRating(value, 85), 85);
    EXPECT_FLOAT_EQ(ESM4::capArmorRating(1000, 0), 1000);
    EXPECT_FLOAT_EQ(ESM4::capArmorRating(1000, 1), 1);
}

TEST(ESM4PhysicalCombat, ArmorSettingsAreTypedAndInvalidInputsFail)
{
    const auto settings = ESM4::buildArmorRatingSettings({});
    EXPECT_FLOAT_EQ(settings.mSkillBase, .35f);
    EXPECT_FLOAT_EQ(settings.mSkillMaximum, 1);
    EXPECT_FLOAT_EQ(settings.mConditionBase, 0);
    EXPECT_FLOAT_EQ(settings.mConditionMultiplier, 1);
    EXPECT_FLOAT_EQ(ESM4::buildMaximumArmorRating({}), 90);
    ESM4::GameSetting maximum{};
    maximum.mEditorId = "fMaxArmorRating";
    maximum.mData = 85.f;
    const std::array<const ESM4::GameSetting*, 1> values{ &maximum };
    EXPECT_FLOAT_EQ(ESM4::buildMaximumArmorRating(values), 85);
    maximum.mData = std::int32_t{85};
    EXPECT_THROW(ESM4::buildMaximumArmorRating(values), std::invalid_argument);
    maximum.mData = -1.f;
    EXPECT_THROW(ESM4::buildMaximumArmorRating(values), std::invalid_argument);
    auto bad = settings;
    bad.mSkillMaximum = .1f;
    EXPECT_THROW(ESM4::armorRating({1400, 50, 50, 1}, bad, installed), std::invalid_argument);
    for (float invalid : {-1.f, std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN()})
    {
        EXPECT_THROW(ESM4::armorRating({1400, 50, 50, invalid}, settings, installed), std::invalid_argument);
        EXPECT_THROW(ESM4::capArmorRating(invalid, 85), std::invalid_argument);
        EXPECT_THROW(ESM4::capArmorRating(85, invalid), std::invalid_argument);
    }
    EXPECT_THROW(ESM4::armorRating({65535, 100, 50, std::numeric_limits<float>::max()}, settings, installed), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, AttackFatigueUsesWeightAndPowerMultiplier)
{
    const ESM4::AttackFatigueSettings settings{7.f, .1f, 5.f};
    // Original 0x547560: R(base + weight*mult), then R(cost*power).
    for (const auto& pair : {std::pair{0.f, 7.f}, {1.f, 7.1f}, {20.f, 9.f}, {100.f, 17.f}, {10000.f, 1007.f}})
    {
        EXPECT_FLOAT_EQ(ESM4::attackFatigueCost(pair.first, false, settings), pair.second);
        EXPECT_FLOAT_EQ(ESM4::attackFatigueCost(pair.first, true, settings), pair.second * 5.f);
    }
    EXPECT_EQ(ESM4::attackFatigueCost(std::nextafter(0.f, 1.f), false, settings), 7.f);
    // A float store occurs before power scaling: halfway above 1 rounds to 1.
    const ESM4::AttackFatigueSettings rounding{1.f, .5f, 2.f};
    EXPECT_EQ(ESM4::attackFatigueCost(std::ldexp(1.f, -23), true, rounding), 2.f);
    EXPECT_EQ(ESM4::attackFatigueCost(100.f, true, {0.f, 0.f, 0.f}), 0.f);
}

TEST(ESM4PhysicalCombat, AttackFatigueRejectsInvalidFactorsAndOverflow)
{
    const ESM4::AttackFatigueSettings settings{7.f, .1f, 5.f};
    for (float invalid : {-1.f, std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN()})
    {
        EXPECT_THROW(ESM4::attackFatigueCost(invalid, false, settings), std::invalid_argument);
        EXPECT_THROW(ESM4::attackFatigueCost(1.f, false, {invalid, .1f, 5.f}), std::invalid_argument);
        EXPECT_THROW(ESM4::attackFatigueCost(1.f, false, {7.f, invalid, 5.f}), std::invalid_argument);
        EXPECT_THROW(ESM4::attackFatigueCost(1.f, false, {7.f, .1f, invalid}), std::invalid_argument);
    }
    EXPECT_THROW(ESM4::attackFatigueCost(std::numeric_limits<float>::max(), true, {1.f, 1.f, 5.f}), std::invalid_argument);
    EXPECT_THROW(ESM4::attackFatigueCost(std::numeric_limits<float>::max(), false, {1.f, 5.f, 1.f}), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, AttackFatigueSettingsUseTypedNativeOverrides)
{
    const auto defaults = ESM4::buildAttackFatigueSettings({});
    EXPECT_FLOAT_EQ(defaults.mBase, 8.f);
    EXPECT_FLOAT_EQ(defaults.mWeightMultiplier, .1f);
    EXPECT_FLOAT_EQ(defaults.mPowerMultiplier, 5.f);
    ESM4::GameSetting base{};
    base.mEditorId = "fFatigueAttackWeaponBase";
    base.mData = 7.f;
    const std::array<const ESM4::GameSetting*, 1> values{&base};
    EXPECT_FLOAT_EQ(ESM4::buildAttackFatigueSettings(values).mBase, 7.f);
    base.mData = std::int32_t{7};
    EXPECT_THROW(ESM4::buildAttackFatigueSettings(values), std::invalid_argument);
    base.mData = -1.f;
    EXPECT_THROW(ESM4::buildAttackFatigueSettings(values), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, CombatMasteryUsesNativeThresholds)
{
    const ESM4::CombatMasterySettings settings{{25, 50, 75, 100}};
    using Rank = ESM4::CombatMastery;
    EXPECT_EQ(ESM4::combatMastery(std::numeric_limits<int>::min(), settings), Rank::Novice);
    EXPECT_EQ(ESM4::combatMastery(0, settings), Rank::Novice);
    EXPECT_EQ(ESM4::combatMastery(1, settings), Rank::Novice);
    for (int tier = 0; tier < 4; ++tier)
    {
        const int threshold = (tier + 1) * 25;
        EXPECT_EQ(ESM4::combatMastery(threshold - 1, settings), static_cast<Rank>(tier));
        EXPECT_EQ(ESM4::combatMastery(threshold, settings), static_cast<Rank>(tier + 1));
        EXPECT_EQ(ESM4::combatMastery(threshold + 1, settings), static_cast<Rank>(tier + 1));
    }
    EXPECT_EQ(ESM4::combatMastery(std::numeric_limits<int>::max(), settings), Rank::Master);
    EXPECT_EQ(ESM4::combatMastery(3, {{1, 2, 3, 4}}), Rank::Expert);
    EXPECT_EQ(ESM4::combatMastery(0, {{0, 0, 0, 0}}), Rank::Master);
}

TEST(ESM4PhysicalCombat, DirectionalPowerMultipliersUnlockIndependently)
{
    const ESM4::CombatMasterySettings mastery{{25, 50, 75, 100}};
    // Deliberately distinct overrides prove selection even though installed
    // side/back/forward settings all happen to equal the novice multiplier.
    const ESM4::PowerAttackSettings settings{2.f, 3.f, 4.f, 5.f, 6.f};
    using Direction = ESM4::PowerAttackDirection;
    struct Case { Direction direction; int threshold; float expected; };
    for (const auto& c : {Case{Direction::Standing, 25, 3.f}, {Direction::Left, 50, 4.f},
             {Direction::Right, 50, 4.f}, {Direction::Backward, 75, 5.f}, {Direction::Forward, 100, 6.f}})
    {
        EXPECT_EQ(ESM4::powerAttackMultiplier(0, c.direction, settings, mastery), 2.f);
        EXPECT_EQ(ESM4::powerAttackMultiplier(c.threshold - 1, c.direction, settings, mastery), 2.f);
        EXPECT_EQ(ESM4::powerAttackMultiplier(c.threshold, c.direction, settings, mastery), c.expected);
        EXPECT_EQ(ESM4::powerAttackMultiplier(c.threshold + 1, c.direction, settings, mastery), c.expected);
        EXPECT_EQ(ESM4::powerAttackMultiplier(1000, c.direction, settings, mastery), c.expected);
    }
    EXPECT_EQ(ESM4::powerAttackMultiplier(100, Direction::Standing, {0, 0, 0, 0, 0}, mastery), 0.f);
}

TEST(ESM4PhysicalCombat, MasteryAndPowerInputsRejectInvalidDomains)
{
    const ESM4::CombatMasterySettings mastery{{25, 50, 75, 100}};
    const ESM4::PowerAttackSettings settings{2.5f, 3.f, 2.5f, 2.5f, 2.5f};
    EXPECT_THROW(ESM4::combatMastery(50, {{-1, 50, 75, 100}}), std::invalid_argument);
    EXPECT_THROW(ESM4::combatMastery(50, {{50, 25, 75, 100}}), std::invalid_argument);
    for (int skill : {0, 100})
        EXPECT_THROW(ESM4::powerAttackMultiplier(skill, static_cast<ESM4::PowerAttackDirection>(99), settings, mastery), std::invalid_argument);
    for (float invalid : {-1.f, std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN()})
        for (float ESM4::PowerAttackSettings::* member : {&ESM4::PowerAttackSettings::mBaseMultiplier,
                 &ESM4::PowerAttackSettings::mStandingMultiplier, &ESM4::PowerAttackSettings::mSideMultiplier,
                 &ESM4::PowerAttackSettings::mBackwardMultiplier, &ESM4::PowerAttackSettings::mForwardMultiplier})
        {
            auto bad = settings;bad.*member = invalid;
            EXPECT_THROW(ESM4::powerAttackMultiplier(0, ESM4::PowerAttackDirection::Standing, bad, mastery), std::invalid_argument);
        }
}

TEST(ESM4PhysicalCombat, MasteryAndPowerSettingsUseNativeTypesAndFallbacks)
{
    EXPECT_EQ(ESM4::buildCombatMasterySettings({}).mMinimumSkill, (std::array<std::int32_t, 4>{25, 50, 75, 100}));
    const auto defaults = ESM4::buildPowerAttackSettings({});
    EXPECT_EQ(defaults.mBaseMultiplier, 3.f);
    EXPECT_EQ(defaults.mStandingMultiplier, 4.f);
    EXPECT_EQ(defaults.mSideMultiplier, 3.f);
    EXPECT_EQ(defaults.mBackwardMultiplier, 3.f);
    EXPECT_EQ(defaults.mForwardMultiplier, 3.f);
    ESM4::GameSetting threshold{}, multiplier{};
    threshold.mEditorId = "iSkillApprenticeMin";threshold.mData = std::int32_t{20};
    multiplier.mEditorId = "fDamagePowerAttackBonus";multiplier.mData = 2.5f;
    const std::array<const ESM4::GameSetting*, 2> values{&threshold, &multiplier};
    EXPECT_EQ(ESM4::buildCombatMasterySettings(values).mMinimumSkill[0], 20);
    EXPECT_EQ(ESM4::buildPowerAttackSettings(values).mBaseMultiplier, 2.5f);
    threshold.mData = 20.f;
    EXPECT_THROW(ESM4::buildCombatMasterySettings(values), std::invalid_argument);
    multiplier.mData = std::int32_t{3};
    EXPECT_THROW(ESM4::buildPowerAttackSettings(values), std::invalid_argument);
}

TEST(ESM4PhysicalCombat, OriginalFirstPunchHealthObservation)
{
    // Original 1.2.0416, M15-S2-ORACLE-HAND-01: ordinary first punch, no
    // equipment/spells on the victim, default difficulty. Console displays
    // victim health 500.00 -> 498.58. Exact contact fatigue was not captured.
    const ESM4::HandToHandSettings hand{0, 1, 0, .75f, 1, 15, 1, .5f};
    const auto full = ESM4::handToHandDamage({10, 50, 40, 1.f}, hand, installed);
    EXPECT_NEAR(500.f - full.mHealth, 498.58f, .0051f);
    // Independently derived lower damage bound if all seven attack fatigue
    // points were still missing at contact: 1 + 14*(.1*.3*.975) = 1.4095.
    const auto depleted = ESM4::handToHandDamage({10, 50, 40, .95f}, hand, installed);
    EXPECT_NEAR(depleted.mHealth, 1.4095f, .00001f);
    EXPECT_LE(depleted.mHealth, full.mHealth);
}
